# Generated by Django 4.2.1 on 2023-05-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
